### ISSUE TITLE
NPC skills don't link to rolls

### ISSUE THREAD

**Issue by Xenobeast** [superseva/mutant-year-zero#24]
Hello,
When clicking on a weapon in a non-mutant (Animal, Robot or Human) actor sheet to bring up the roller, I get a notification stating it can't link to a relevant skill. I have tried both with items I have added into the compendium, and those created only on the Actor sheet, and with PC and NPC sheets. These same attacks work for Mutant actors.

![NoSkill](https://user-images.githubusercontent.com/11707798/112707554-85a7a980-8e69-11eb-990e-8900c2efef58.png)

**Comment by Xenobeast** [comment]
Figures, as soon as I post, I figure it out. Well, narrow it down anyway. I created a new skill compendium to include descriptions, and the system doesn't recognize them when pulling info into the roller. The Mutant actor I mentioned above was created using the original compendium before I created my own. I tested using a new mutant actor, and no dice. So the issue is the system won't pull user created skills into the roller automatically.

**Comment by superseva** [comment]
So here's what is actually happening.
each skill from the core compendium has a property called "skillKey". This non-editable property is used to identify a skill even if the name of the skill is translated.
So when using a weapon the system will look for a skill on the character with one of those skillKeys ( SHOOTING, FIGHTING or ASSAULT). Try exporting one of the skills in your game and check the exported json if it has "skillKey" value assigned.
The latest version of MYZ is 0.99.
IMPORTANT:
just keep a backup version of the skill compendium with descriptions you've made since the system will override 'core' compendiums once you pull an update. Keep the edited compendium somewhere on your machine so you can drop it in the system again once the system gets updated.
