### ISSUE TITLE
Swedish translation?

### ISSUE THREAD

**Issue by salacious8crumb** [superseva/mutant-year-zero#35]
I have completed a Swedish translation of the system. Please consider adding it to a future release.
[se.docx](https://github.com/superseva/mutant-year-zero/files/6825828/se.docx)

**Comment by superseva** [comment]
Hey, thanks for the translation. I will be glad to include it. Before I do it would you mind checking it against the latest eng file. Some new entries are added, I think mainly the names of all the other skills from the rest of the books. You can use a site like http://www.jsondiff.com/ to see what is the difference between those two jsons, and what shuold be added to a Swedish one.
When you copy your json to check the differences  just change the quotation symbol before “Skydd" so you don't get an error.
This is the line that can cause you the trouble ``` "MYZ.ARMOR_RATING": “Skydd ", ```
I can use it as it is now but it won't cover all the translations since there is are few more words in the default english file.
Thanks again

**Comment by salacious8crumb** [comment]
Thanks for the quick response. I have updated the file and added the new values, as well as corrected a few mistakes I made in the original. I also noted two typos in the English version, namely "Borken" (line 60) and "Equiped" (line 91). I submit my new Swedish language file here.
[se.docx](https://github.com/superseva/mutant-year-zero/files/6834631/se.docx)

**Comment by superseva** [comment]
Thank. "Borken" was mentioned before but we left it as a joke :)
I am pushing this tomorrow. Thanks for the help

**Comment by superseva** [comment]
Added in v1.5
