### ISSUE TITLE
Possible future updates?

### ISSUE THREAD

**Issue by WyntherKnight** [superseva/mutant-year-zero#7]
Great job on making MYZ game system for foundry. Some features that would be nice to be added if you can.
1) feature to show the description of Skills on chat (like the speech bubble icon on the mutations/powers/talents).
2) actor for monster and threats which includes their "Known Nature" modifier (at the moment we are using the npc actor)
3) icons of mutations/powers/talents to show on the character sheet, just like with gears and equipment
4) A place for inputing Appearance and Den information 

Thanks!

**Comment by superseva** [comment]
Hey, thanks for the suggestions. 
1. I'll add this icon in the right-click-menu since there is not much space to add an icon next to the name/attr and bonus field
2. I'll add "KNOW THE ZONE" filed to the NPC. I would use journal for phenomena. (Since the official content is being created atm I'll see that those  journal headers have some styling that includes "KNOW THE ZONE" value
3. It's really a space problem, or a lack of it. I would also love to see those but still haven't got good solution for the lack of space (I don't wanna increase the width of the sheet since it's already pretty wide)
4. Den for Animal Mutants ? Yeah, you can probably use INFO tab since it is big enough and it can be formatted with styles and tables

**Comment by WyntherKnight** [comment]
Thanks for the reply! Yeah, we kinda started with Genlab alpha and i just realised that there are 4 different kinds of core character sheets. If I find anything else to suggest to help improve this, I'll post it again.

**Comment by WyntherKnight** [comment]
Hi again, 

Can you also add gear and artifact boxes for the NPC? I've been transferring NPC information from the book to the foundry game and almost all of them have gears (not wepaons or armor) and some have artifacts. At the moment, I'm just writing the gear/artifact under the Special box. Thanks!

**Comment by superseva** [comment]
I can't seems to find any artifacts or gear listed in the book when describing threats of the Zone. NPC sheets are meant for that. They are just short version of character sheet. If you need your NPCs to have gear, artifacts or anything else consider using Character sheet for it.

**Comment by superseva** [comment]
ah, I see a gear or two in 'adventure' books.
I need to think about adding it without making NPC sheet same as Character sheet

**Comment by superseva** [comment]
fopr now you can always drag and drop items and actors to the info area to create links to them.
Since some of the "npc"s have only one or two of those, and most of them don't have that in core-books I would suggest adding those there. You can also "format" the style of the text or even create two tables there one for gear and one for artifacts

**Comment by WyntherKnight** [comment]
Thanks again for the reply! I think the drag and drop will work well. Yeah, its mostly for the NPCs in the adventure parts of the book.

**Comment by MirthaLeGrand** [comment]
Hey! First of all, thanks so much for this System! I think it's gonna be a lifesaver until we get vaccinated where I live. 

I would like to add a suggestion as well! 

The alien RPG module has a great feature, where you can modify Char Sheets to show the stunt options with a button beside the Skill. This would be a godsend. My group is a casual one, and often we default to the most used Stunt instead of thinking of the most appropiate/fun one. 

If at all possible, I think a few item/actor types should be added. These are both from genlab alpha since I'm currently building a new campaign for it, so I cant' speak for the other modules:

An actor or item option for Genlab Alpha's Resistance Sheet and Watcher sheet would prevent going off foundry to fill a pdf manually,

**Comment by superseva** [comment]
Those might get added in the future, after MYZ official release. For now
you can use fillable PDFs ingame with the PDFoundry module

**Comment by superseva** [comment]
> The alien RPG module has a great feature, where you can modify Char Sheets to show the stunt options with a button beside the Skill. This would be a godsend. My group is a casual one, and often we default to the most used Stunt instead of thinking of the most appropiate/fun one.

Skill to chat button will be added soon. I am in a process of prepping official content so that's why the things with updates are a bit delayed. This will post the skill description ( stunts) to the chat

**Comment by superseva** [comment]
added to project task list
